export interface MilkyApi {
  name: string
  label: string
  group: string
}

export const milkyApis = [
  { name: 'get_login_info', label: '获取登录信息', group: '系统' },
  { name: 'get_impl_info', label: '获取协议端信息', group: '系统' },
  { name: 'get_user_profile', label: '获取用户个人信息', group: '系统' },
  { name: 'get_friend_list', label: '获取好友列表', group: '系统' },
  { name: 'get_friend_info', label: '获取好友信息', group: '系统' },
  { name: 'get_group_list', label: '获取群列表', group: '系统' },
  { name: 'get_group_info', label: '获取群信息', group: '系统' },
  { name: 'get_group_member_list', label: '获取群成员列表', group: '系统' },
  { name: 'get_group_member_info', label: '获取群成员信息', group: '系统' },
  { name: 'get_peer_pins', label: '获取置顶好友和群', group: '系统' },
  { name: 'set_peer_pin', label: '设置好友或群置顶', group: '系统' },
  { name: 'set_avatar', label: '设置账号头像', group: '系统' },
  { name: 'set_nickname', label: '设置账号昵称', group: '系统' },
  { name: 'set_bio', label: '设置个性签名', group: '系统' },
  { name: 'get_custom_face_url_list', label: '获取自定义表情列表', group: '系统' },
  { name: 'get_cookies', label: '获取 Cookies', group: '系统' },
  { name: 'get_csrf_token', label: '获取 CSRF Token', group: '系统' },
  { name: 'send_private_message', label: '发送私聊消息', group: '消息' },
  { name: 'send_group_message', label: '发送群聊消息', group: '消息' },
  { name: 'recall_private_message', label: '撤回私聊消息', group: '消息' },
  { name: 'recall_group_message', label: '撤回群聊消息', group: '消息' },
  { name: 'get_message', label: '获取消息', group: '消息' },
  { name: 'get_history_messages', label: '获取历史消息', group: '消息' },
  { name: 'get_resource_temp_url', label: '获取临时资源链接', group: '消息' },
  { name: 'get_forwarded_messages', label: '获取合并转发消息', group: '消息' },
  { name: 'mark_message_as_read', label: '标记消息为已读', group: '消息' },
  { name: 'send_friend_nudge', label: '发送好友戳一戳', group: '好友' },
  { name: 'send_profile_like', label: '发送名片点赞', group: '好友' },
  { name: 'delete_friend', label: '删除好友', group: '好友' },
  { name: 'get_friend_requests', label: '获取好友请求', group: '好友' },
  { name: 'accept_friend_request', label: '同意好友请求', group: '好友' },
  { name: 'reject_friend_request', label: '拒绝好友请求', group: '好友' },
  { name: 'set_group_name', label: '设置群名称', group: '群聊' },
  { name: 'set_group_avatar', label: '设置群头像', group: '群聊' },
  { name: 'set_group_member_card', label: '设置群名片', group: '群聊' },
  { name: 'set_group_member_special_title', label: '设置群成员头衔', group: '群聊' },
  { name: 'set_group_member_admin', label: '设置群管理员', group: '群聊' },
  { name: 'set_group_member_mute', label: '设置群成员禁言', group: '群聊' },
  { name: 'set_group_whole_mute', label: '设置群全员禁言', group: '群聊' },
  { name: 'kick_group_member', label: '踢出群成员', group: '群聊' },
  { name: 'get_group_announcements', label: '获取群公告', group: '群聊' },
  { name: 'send_group_announcement', label: '发送群公告', group: '群聊' },
  { name: 'delete_group_announcement', label: '删除群公告', group: '群聊' },
  { name: 'get_group_essence_messages', label: '获取群精华消息', group: '群聊' },
  { name: 'set_group_essence_message', label: '设置群精华消息', group: '群聊' },
  { name: 'quit_group', label: '退出群聊', group: '群聊' },
  { name: 'send_group_message_reaction', label: '发送群消息回应', group: '群聊' },
  { name: 'send_group_nudge', label: '发送群戳一戳', group: '群聊' },
  { name: 'get_group_notifications', label: '获取群通知', group: '群聊' },
  { name: 'accept_group_request', label: '同意入群请求', group: '群聊' },
  { name: 'reject_group_request', label: '拒绝入群请求', group: '群聊' },
  { name: 'accept_group_invitation', label: '同意群邀请', group: '群聊' },
  { name: 'reject_group_invitation', label: '拒绝群邀请', group: '群聊' },
  { name: 'upload_private_file', label: '上传私聊文件', group: '文件' },
  { name: 'upload_group_file', label: '上传群文件', group: '文件' },
  { name: 'get_private_file_download_url', label: '获取私聊文件链接', group: '文件' },
  { name: 'get_group_file_download_url', label: '获取群文件链接', group: '文件' },
  { name: 'get_group_files', label: '获取群文件列表', group: '文件' },
  { name: 'move_group_file', label: '移动群文件', group: '文件' },
  { name: 'rename_group_file', label: '重命名群文件', group: '文件' },
  { name: 'delete_group_file', label: '删除群文件', group: '文件' },
  { name: 'create_group_folder', label: '创建群文件夹', group: '文件' },
  { name: 'rename_group_folder', label: '重命名群文件夹', group: '文件' },
  { name: 'delete_group_folder', label: '删除群文件夹', group: '文件' },
] as const satisfies readonly MilkyApi[]
